version: '3.4'

services:
  api:
    build:
      context: .
      target: test
    image: 'cookie-quest-api:dev'
    volumes:
      - ./:/cookie-quest
    ports:
      - '3000:3000'
    command: npm run start:watch
